/** Declaration file generated by dts-gen */

export const components: {
  InnerSlider: {
    beforeDestroy: any
    components: {
      SliderArrow: {
        name: string
        props: string[]
        render: any
      }
      SliderDots: {
        name: string
        props: string[]
        render: any
      }
      SliderTrack: {
        methods: {
          cloneSlide: any
          renderSlides: any
        }
        name: string
        props: string[]
        render: any
      }
    }
    computed: {
      slideCount: any
      spec: any
    }
    created: any
    data: any
    inheritAttrs: boolean
    methods: {
      adaptHeight: any
      autoPlay: any
      changeSlide: any
      checkImagesLoad: any
      clickHandler: any
      goTo: any
      keyHandler: any
      next: any
      onDotsLeave: any
      onDotsOver: any
      onPropsUpdated: any
      onSlideBlur: any
      onSlideFocus: any
      onTrackLeave: any
      onTrackOver: any
      onWindowResized: any
      pause: any
      play: any
      prev: any
      progressiveLazyLoad: any
      resizeWindow: any
      selectHandler: any
      slideHandler: any
      ssrInit: any
      swipeEnd: any
      swipeMove: any
      swipeStart: any
      updateState: any
    }
    mixins: {
      computed: {
        isPropsUpdated: any
      }
      watch: {
        isPropsUpdated: any
      }
    }[]
    mounted: any
    name: string
    props: {
      accessibility: {
        default: boolean
        type: any
      }
      adaptiveHeight: {
        default: boolean
        type: any
      }
      arrows: {
        default: boolean
        type: any
      }
      asNavFor: {
        default: any
        type: any
      }
      autoplay: {
        default: boolean
        type: any
      }
      autoplaySpeed: {
        default: number
        type: any
      }
      centerMode: {
        default: boolean
        type: any
      }
      centerPadding: {
        default: string
        type: any
      }
      cssEase: {
        default: string
        type: any
      }
      customPaging: any
      dots: {
        default: boolean
        type: any
      }
      dotsClass: {
        default: string
        type: any
      }
      draggable: {
        default: boolean
        type: any
      }
      edgeFriction: {
        default: number
        type: any
      }
      fade: {
        default: boolean
        type: any
      }
      focusOnSelect: {
        default: boolean
        type: any
      }
      infinite: {
        default: boolean
        type: any
      }
      initialSlide: {
        default: number
        type: any
      }
      lazyLoad: {
        default: any
        type: any
      }
      nextArrow: any
      pauseOnDotsHover: {
        default: boolean
        type: any
      }
      pauseOnFocus: {
        default: boolean
        type: any
      }
      pauseOnHover: {
        default: boolean
        type: any
      }
      prevArrow: any
      responsive: {
        default: any
        type: any
      }
      rows: {
        default: number
        type: any
      }
      rtl: {
        default: boolean
        type: any
      }
      slidesPerRow: {
        default: number
        type: any
      }
      slidesToScroll: {
        default: number
        type: any
      }
      slidesToShow: {
        default: number
        type: any
      }
      speed: {
        default: number
        type: any
      }
      swipe: {
        default: boolean
        type: any
      }
      swipeToSlide: {
        default: boolean
        type: any
      }
      touchMove: {
        default: boolean
        type: any
      }
      touchThreshold: {
        default: number
        type: any
      }
      unslick: {
        default: boolean
        type: any
      }
      useCSS: {
        default: boolean
        type: any
      }
      useTransform: {
        default: boolean
        type: any
      }
      variableWidth: {
        default: boolean
        type: any
      }
      vertical: {
        default: boolean
        type: any
      }
      waitForAnimate: {
        default: boolean
        type: any
      }
    }
    render: any
    updated: any
  }
}

export const inheritAttrs: boolean

export const mixins: {
  computed: {
    isPropsUpdated: any
  }
  watch: {
    isPropsUpdated: any
  }
}[]

export const name: string

export const props: {
  accessibility: {
    default: boolean
    type: any
  }
  adaptiveHeight: {
    default: boolean
    type: any
  }
  arrows: {
    default: boolean
    type: any
  }
  asNavFor: {
    default: any
    type: any
  }
  autoplay: {
    default: boolean
    type: any
  }
  autoplaySpeed: {
    default: number
    type: any
  }
  centerMode: {
    default: boolean
    type: any
  }
  centerPadding: {
    default: string
    type: any
  }
  cssEase: {
    default: string
    type: any
  }
  dots: {
    default: boolean
    type: any
  }
  dotsClass: {
    default: string
    type: any
  }
  draggable: {
    default: boolean
    type: any
  }
  edgeFriction: {
    default: number
    type: any
  }
  fade: {
    default: boolean
    type: any
  }
  focusOnSelect: {
    default: boolean
    type: any
  }
  infinite: {
    default: boolean
    type: any
  }
  initialSlide: {
    default: number
    type: any
  }
  lazyLoad: {
    default: any
    type: any
  }
  pauseOnDotsHover: {
    default: boolean
    type: any
  }
  pauseOnFocus: {
    default: boolean
    type: any
  }
  pauseOnHover: {
    default: boolean
    type: any
  }
  responsive: {
    default: any
    type: any
  }
  rows: {
    default: number
    type: any
  }
  rtl: {
    default: boolean
    type: any
  }
  slidesPerRow: {
    default: number
    type: any
  }
  slidesToScroll: {
    default: number
    type: any
  }
  slidesToShow: {
    default: number
    type: any
  }
  speed: {
    default: number
    type: any
  }
  swipe: {
    default: boolean
    type: any
  }
  swipeToSlide: {
    default: boolean
    type: any
  }
  touchMove: {
    default: boolean
    type: any
  }
  touchThreshold: {
    default: number
    type: any
  }
  useCSS: {
    default: boolean
    type: any
  }
  useTransform: {
    default: boolean
    type: any
  }
  variableWidth: {
    default: boolean
    type: any
  }
  vertical: {
    default: boolean
    type: any
  }
  waitForAnimate: {
    default: boolean
    type: any
  }
}

export function beforeDestroy(): void

export function created(): void

export function data(): any

export function render(...args: any[]): any

export namespace computed {
  function settings(): any
}

export namespace methods {
  function clearBreakpoints(): any

  function goTo(slide: any, ...args: any[]): void

  function makeBreakpoints(): any

  function media(query: any, handler: any): void

  function next(): void

  function onPropsUpdated(): void

  function pause(): void

  function play(): void

  function prev(): void
}
